### ISSUE TITLE
Multiplayer won't work 1.4.3 Legacy

### ISSUE THREAD

**Issue by ZachAttack5321** [jjohnsnaill/SubworldLibrary#29] opened 2023-08-02 07:28 UTC
At the time of posting this, there has been quite a moderate uproar on the steam workshop page of the mod, and there have been some people there saying that this mod fails to run. 

Loading into a Singleplayer world works fine, I've heard there are issues here and there but that's all I know. 
Loading into a Multiplayer world, however, causes the mod to give up and Disable itself. I forgot what error code popped up the first time this happened, and haven't tried to replicate the exact conditions, but others have pasted their error messages onto the steam Workshop. 

At the moment, multiplayer is impossible and other dependent mods like 'Stars Above' and 'Infernum Mode' will not enable and force itself to disable upon loading the world. That is all, hope all goes well and this issue is resolved at your convenience. Thank you.

**Comment by jjohnsnaill** [comment] 2023-08-02 21:18
Duplicate of #27.

**Closed by jjohnsnaill** 2023-08-02 21:18 UTC
