### ISSUE TITLE
Background issue

### ISSUE THREAD

**Issue by Silvernova115** [jjohnsnaill/SubworldLibrary#4] opened 2022-06-04 01:13 UTC
When im in the underworld, the background doesnt show. it does show up if I disable this mod.

**Comment by Opnoob007** [comment] 2022-06-11 06:42
I also have this issue if I use this mod please fix this

**Comment by WinterEquinoxAlpha** [comment] 2022-06-12 01:51
Error reproduced on my machine as well

**Comment by TerraLance** [comment] 2022-06-16 21:23
Reproduced here

**Comment by YellowBirb** [comment] 2022-07-03 09:09
I noticed this too, and im not sure whether underworld enemies have stopped spawning because of this. v1.4.3.6 tModLoader v2022.6.96.4

**Comment by jjohnsnaill** [comment] 2022-10-05 11:33
Fixed in 2.0.1.2. It was just the background that wasn't appearing.

**Closed by jjohnsnaill** 2022-10-05 11:33 UTC
