### ISSUE TITLE
Infernum mod's Lost coliseum subworld doesn't work in MP

### ISSUE THREAD

**Issue by SomeRandomGuyl** [jjohnsnaill/SubworldLibrary#13] opened 2023-02-04 02:20 UTC
The lost coliseum subworld in the Infernum Mod doesn't work in MP
They claim that it is on this mod's end that is having the issue and not Infernum's end

**Comment by jjohnsnaill** [comment] 2023-02-04 21:46
Duplicate of #12.

**Closed by jjohnsnaill** 2023-02-04 21:46 UTC
