### ISSUE TITLE
1.4.4 multiplayer dont work subworld

### ISSUE THREAD

**Issue by FilimonEnc** [jjohnsnaill/SubworldLibrary#28] opened 2023-08-02 04:10 UTC
[07:08:21.789] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\SteamLibrary\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" tModLoader.dll -server -showserverconsole -world "tModLoader/worlds/Карантин_скользких_теней.wld" -subworld "StarsAbove/Observatory"
[07:08:45.648] [Main Thread/WARN] [tML]: Бесшумно пойманное исключение: 
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at SubworldLibrary.SubserverLink.Send(Byte[] data) in SubworldLibrary.cs:line 982
   at SubworldLibrary.SubworldLibrary.DenyRead(MessageBuffer buffer, Int32 start, Int32 length) in SubworldLibrary.cs:line 645
   at DMD<System.Void Terraria.NetMessage:CheckBytes(System.Int32)>(Int32 bufferIndex)
   at SyncProxy<System.Void Terraria.NetMessage:CheckBytes(System.Int32)>(Int32 )
   at Terraria.Netplay.UpdateServerInMainThread() in tModLoader\Terraria\Netplay.cs:line 59
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 14155
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 14054
   at DMD<System.Void Terraria.Main:DedServ_PostModLoad(System.Boolean&)>(Main this, Boolean& reloadMods)
   at SyncProxy<System.Void Terraria.Main:DedServ_PostModLoad(System.Boolean&)>(Main , Boolean& )
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4516
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 264
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 215
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 71
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 57
   at System.Threading.Thread.StartCallback()

[07:08:45.755] [Main Thread/ERROR] [Network]: [0][127.0.0.1:62935 (Atherius)] Unknown(-1)
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at SubworldLibrary.SubserverLink.Send(Byte[] data) in SubworldLibrary.cs:line 982
   at SubworldLibrary.SubworldLibrary.DenyRead(MessageBuffer buffer, Int32 start, Int32 length) in SubworldLibrary.cs:line 645
   at DMD<System.Void Terraria.NetMessage:CheckBytes(System.Int32)>(Int32 bufferIndex)

**Comment by jjohnsnaill** [comment] 2023-08-02 21:16
Duplicate of #26.

**Closed by jjohnsnaill** 2023-08-02 21:16 UTC
